import { query, queryOne, withTransaction } from './pool.js';

const QUIZ_SELECT = `
  SELECT q.id, q.study_kit_id, q.source_id, q.title, q.language, q.difficulty,
         q.question_count, q.status, q.created_at`;

export const quizDb = {
  async saveGenerated({ cacheId, source, quiz, params, model }) {
    return withTransaction(async (client) => {
      const inserted = (await client.query(
        `INSERT INTO quizzes
           (study_kit_id, source_id, generation_cache_id, title, language, difficulty,
            question_count, generated_by_ai, status, description)
         VALUES ($1, $2, $3, $4, $5, $6, $7, true, 'ready', $8)
         ON CONFLICT (generation_cache_id) WHERE generation_cache_id IS NOT NULL
         DO UPDATE SET title = EXCLUDED.title
         RETURNING id`,
        [source.study_kit_id, source.id, cacheId, quiz.title, params.language,
          params.difficulty, quiz.questions.length, `Generated by ${model}`],
      )).rows[0];

      for (const [position, question] of quiz.questions.entries()) {
        const topic = question.topic
          ? (await client.query(
              `INSERT INTO topics (study_kit_id, name) VALUES ($1, $2)
               ON CONFLICT (study_kit_id, name) WHERE study_kit_id IS NOT NULL
               DO UPDATE SET name = EXCLUDED.name RETURNING id`,
              [source.study_kit_id, question.topic],
            )).rows[0]
          : null;
        await client.query(
          `INSERT INTO quiz_questions
             (quiz_id, position, kind, prompt, options, correct_answer, explanation,
              topic_label, topic_id, targeted_weak_concept)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
           ON CONFLICT (quiz_id, position) DO NOTHING`,
          [inserted.id, position, question.kind, question.prompt,
            JSON.stringify(question.options), JSON.stringify(question.correctAnswer),
            question.explanation, question.topic, topic?.id ?? null,
            question.targetedWeakConcept ?? null],
        );
      }
      await client.query(`UPDATE ai_generation_cache SET status = 'ready', error_message = NULL WHERE id = $1`, [cacheId]);
      return inserted;
    });
  },

  /**
   * The questions this student has already been asked about this material.
   *
   * Scoped to questions they actually ANSWERED, not merely every question ever
   * generated: an abandoned quiz they never opened is not something they have
   * seen, and excluding it would burn the good questions for nothing.
   *
   * Newest first and capped, because this list goes into the prompt. An old
   * question is the safest one to forget — it is the least likely to still be
   * fresh in the student's mind, and the prompt has a budget.
   */
  async seenQuestions({ userId, sourceId, limit = 60 }) {
    const { rows } = await query(
      `SELECT DISTINCT ON (qq.id) qq.prompt, a.answered_at
         FROM quiz_attempt_answers a
         JOIN quiz_attempts att ON att.id = a.attempt_id
         JOIN quiz_questions qq ON qq.id = a.question_id
         JOIN quizzes q ON q.id = qq.quiz_id
        WHERE att.user_id = $1 AND q.source_id = $2
        ORDER BY qq.id, a.answered_at DESC`,
      [userId, sourceId],
    );
    return rows
      .sort((a, b) => b.answered_at - a.answered_at)
      .slice(0, limit)
      .map((row) => row.prompt);
  },

  /**
   * What this student keeps getting wrong on this material, worst first.
   *
   * Read from answers on THIS source rather than from `user_topic_mastery`,
   * which is account-wide: a topic they are weak at in another kit says nothing
   * about the document in front of them, and this quiz can only ask about this
   * document. Mastery is still used as the tie-break, so a topic they are
   * generally shaky on outranks one they merely slipped on once.
   *
   * A topic only counts as weak once it has been answered wrong at least once;
   * "never asked" is not the same as "weak" and must not crowd out the 30%.
   */
  async weakTopics({ userId, sourceId, limit = 6 }) {
    const { rows } = await query(
      `SELECT qq.topic_label AS topic,
              count(*) FILTER (WHERE a.is_correct IS FALSE)::int AS wrong,
              count(*)::int AS asked,
              COALESCE(min(m.mastery_percent), 100)::int AS mastery
         FROM quiz_attempt_answers a
         JOIN quiz_attempts att ON att.id = a.attempt_id
         JOIN quiz_questions qq ON qq.id = a.question_id
         JOIN quizzes q ON q.id = qq.quiz_id
         LEFT JOIN user_topic_mastery m ON m.topic_id = qq.topic_id AND m.user_id = $1
        WHERE att.user_id = $1 AND q.source_id = $2
          AND qq.topic_label IS NOT NULL AND qq.topic_label <> ''
        GROUP BY qq.topic_label
       HAVING count(*) FILTER (WHERE a.is_correct IS FALSE) > 0
        ORDER BY (count(*) FILTER (WHERE a.is_correct IS FALSE))::float / count(*) DESC,
                 min(m.mastery_percent) ASC NULLS LAST
        LIMIT $3`,
      [userId, sourceId, limit],
    );
    return rows;
  },

  /**
   * How many quizzes on this material this student has already finished.
   *
   * It is the round number, and it goes into the generation cache key — which
   * is what makes "generate another" actually generate another. Without it the
   * key is the same every time and the student is handed back the quiz they
   * just sat.
   */
  async completedRounds({ userId, sourceId }) {
    const row = await queryOne(
      `SELECT count(DISTINCT att.id)::int AS rounds
         FROM quiz_attempts att
         JOIN quizzes q ON q.id = att.quiz_id
        WHERE att.user_id = $1 AND q.source_id = $2 AND att.status = 'submitted'`,
      [userId, sourceId],
    );
    return row?.rounds ?? 0;
  },

  async byCache(cacheId) {
    return queryOne(`${QUIZ_SELECT} FROM quizzes q WHERE q.generation_cache_id = $1`, [cacheId]);
  },

  async questions(quizId, { answersForAttemptId = null } = {}) {
    const { rows } = await query(
      `SELECT qq.id, qq.position, qq.kind, qq.prompt, qq.options, qq.explanation,
              qq.topic_label, qq.targeted_weak_concept, a.response, a.is_correct, a.answered_at,
              CASE WHEN a.id IS NULL THEN NULL ELSE qq.correct_answer END AS revealed_answer
         FROM quiz_questions qq
         LEFT JOIN quiz_attempt_answers a
           ON a.question_id = qq.id AND a.attempt_id = $2
        WHERE qq.quiz_id = $1 ORDER BY qq.position`,
      [quizId, answersForAttemptId],
    );
    return rows;
  },

  async startAttempt({ userId, quizId }) {
    return withTransaction(async (client) => {
      const quiz = (await client.query(
        `SELECT q.id, q.question_count FROM quizzes q
         JOIN study_kits k ON k.id = q.study_kit_id
         WHERE q.id = $1 AND k.user_id = $2 AND q.status = 'ready'`,
        [quizId, userId],
      )).rows[0];
      if (!quiz) return null;
      return (await client.query(
        `INSERT INTO quiz_attempts (quiz_id, user_id, total_questions)
         VALUES ($1, $2, $3) RETURNING *`, [quizId, userId, quiz.question_count],
      )).rows[0];
    });
  },

  async attempt({ userId, attemptId }) {
    return queryOne(
      `SELECT a.*, q.title AS quiz_title, q.study_kit_id, q.language
         FROM quiz_attempts a JOIN quizzes q ON q.id = a.quiz_id
        WHERE a.id = $1 AND a.user_id = $2`, [attemptId, userId],
    );
  },

  async saveAnswer({ userId, attemptId, questionId, response, timeSpentSeconds }) {
    return withTransaction(async (client) => {
      const row = (await client.query(
        `SELECT a.id, a.status, qq.correct_answer, qq.kind
           FROM quiz_attempts a JOIN quiz_questions qq ON qq.quiz_id = a.quiz_id
          WHERE a.id = $1 AND a.user_id = $2 AND qq.id = $3 FOR UPDATE`,
        [attemptId, userId, questionId],
      )).rows[0];
      if (!row || row.status !== 'in_progress') return null;
      const expected = row.correct_answer;
      const isCorrect = typeof expected === 'string'
        ? String(response).trim().toLocaleLowerCase() === expected.trim().toLocaleLowerCase()
        : response === expected;
      return (await client.query(
        `INSERT INTO quiz_attempt_answers
           (attempt_id, question_id, response, is_correct, time_spent_seconds)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (attempt_id, question_id) DO UPDATE
           SET response = EXCLUDED.response, is_correct = EXCLUDED.is_correct,
               time_spent_seconds = EXCLUDED.time_spent_seconds, answered_at = now()
         RETURNING response, is_correct, answered_at`,
        [attemptId, questionId, JSON.stringify(response), isCorrect, timeSpentSeconds ?? null],
      )).rows[0];
    });
  },

  async submitStats({ userId, attemptId }) {
    return withTransaction(async (client) => {
      const attempt = (await client.query(
        `SELECT a.*, q.title AS quiz_title, q.language FROM quiz_attempts a
         JOIN quizzes q ON q.id = a.quiz_id
         WHERE a.id = $1 AND a.user_id = $2 FOR UPDATE`, [attemptId, userId],
      )).rows[0];
      if (!attempt || attempt.status !== 'in_progress') return attempt ?? null;
      const stats = (await client.query(
        `SELECT count(*) FILTER (WHERE is_correct)::int AS correct,
                array_remove(array_agg(qq.topic_label) FILTER (WHERE NOT a.is_correct), NULL) AS missed_topics
           FROM quiz_attempt_answers a JOIN quiz_questions qq ON qq.id = a.question_id
          WHERE a.attempt_id = $1`, [attemptId],
      )).rows[0];
      return { ...attempt, computedCorrect: stats.correct ?? 0, missedTopics: stats.missed_topics ?? [] };
    });
  },

  async finishAttempt({ userId, attemptId, correct, mastery, takeaways }) {
    return queryOne(
      `UPDATE quiz_attempts SET status = 'submitted', correct_count = $3,
              mastery_percent = $4, takeaways = $5, submitted_at = now()
        WHERE id = $1 AND user_id = $2 AND status = 'in_progress' RETURNING *`,
      [attemptId, userId, correct, mastery, JSON.stringify(takeaways)],
    );
  },
};
