import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { CheckIcon } from '../../components/ui.jsx';
import { useT } from '../../i18n/index.js';
import { api } from '../../lib/api.js';
import { NavyHeader } from '../../layouts/AppLayout.jsx';
import { Owl } from '../../layouts/AuthLayout.jsx';

export const PracticeResultsPage=()=>{const t=useT();const [params]=useSearchParams();const id=params.get('sessionId')||window.localStorage.getItem('reanmate:practice-session');const [result,setResult]=useState(null);useEffect(()=>{if(id)api.get(`/practice/sessions/${id}`).then(({data})=>setResult({...data.session,total:data.session.questionCount,toReview:data.session.answered-data.session.correct}));},[id]);return <main><NavyHeader><Link to="/practice" aria-label={t('common.back')}>← {t('practice.completeTitle')}</Link></NavyHeader><div className="px-5 pt-6"><div className="text-center"><Owl variant="waving" className="mx-auto size-24" /><h2 className="text-2xl font-bold text-navy-900">{t('practice.completeTitle')}</h2><p className="text-navy-600">{t('practice.completeSubtitle',{count:result?.total??0})}</p></div><div className="mt-5 rounded-card bg-tint-100 py-7 text-center"><p className="text-5xl font-bold text-navy-900">{result?.correct??0} / {result?.total??0}</p><p className="text-navy-600">{t('quiz.correctAnswers')}</p></div><section className="mt-4 rounded-card bg-white p-5 ring-1 ring-tint-200"><p className="text-xl font-bold text-navy-900">{t('quiz.mastery',{percent:result?.mastery??0})}</p><div className="mt-2 h-2.5 bg-tint-100"><span className="block h-full bg-navy-800" style={{width:`${result?.mastery??0}%`}} /></div></section><ul className="mt-4 rounded-card bg-white px-5 ring-1 ring-tint-200"><li className="flex gap-3 py-3"><span className="grid size-7 place-items-center rounded-full bg-navy-800"><CheckIcon /></span>{t('practice.correctCount',{count:result?.correct??0})}</li><li className="py-3">{t('practice.toReview',{count:result?.toReview??0})}</li></ul><section className="mt-4 rounded-card bg-white p-5 ring-1 ring-tint-200"><h3 className="text-xl font-bold text-navy-900">{t('practice.whatToReview')}</h3><ul>{(result?.weakTopics??[]).map((topic)=><li key={topic} className="py-2 text-navy-800">{topic}</li>)}</ul></section></div></main>;};
