import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '../../components/ui.jsx';
import { useT } from '../../i18n/index.js';
import { api } from '../../lib/api.js';
import { NavyHeader } from '../../layouts/AppLayout.jsx';
import { Owl } from '../../layouts/AuthLayout.jsx';

export const PracticeSessionPage=()=>{const t=useT();const navigate=useNavigate();const [params]=useSearchParams();const id=params.get('sessionId')||window.localStorage.getItem('reanmate:practice-session');const [data,setData]=useState(null);const [seconds,setSeconds]=useState(null);useEffect(()=>{if(id)api.get(`/practice/sessions/${id}`).then(({data:result})=>{setData(result);setSeconds(result.session.timerSeconds);});},[id]);useEffect(()=>{if(!data?.session.timerSeconds)return undefined;const timer=window.setInterval(()=>setSeconds((value)=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer);},[data?.session.timerSeconds]);const answers=useMemo(()=>Object.fromEntries((data?.questions??[]).filter((q)=>q.answeredAt).map((q)=>[q.position,q.response])),[data]);const save=async(position,response)=>{await api.put(`/practice/sessions/${id}/answers`,{position,response});setData((current)=>({...current,questions:current.questions.map((q)=>q.position===position?{...q,response,answeredAt:new Date().toISOString()}:q)}));};const submit=async()=>{const elapsed=(data.session.timerSeconds||0)-(seconds||0);await api.post(`/practice/sessions/${id}/submit`,{durationSeconds:Math.max(0,elapsed)});navigate(`/practice/results?sessionId=${id}`);};const total=data?.questions.length??0;return <main><NavyHeader className="flex items-center justify-between"><Link to="/practice" aria-label={t('common.back')}>← {t('practice.title')}</Link>{data?.session.timerSeconds>0&&<span className="rounded-full bg-white/15 px-4 py-2 font-bold">{t('practice.timeLeft',{time:`${String(Math.floor((seconds??0)/60)).padStart(2,'0')}:${String((seconds??0)%60).padStart(2,'0')}`})}</span>}</NavyHeader><div className="px-5 pt-5"><div className="flex justify-between"><div><h2 className="text-2xl font-bold text-navy-900">{t('practice.answerAll',{count:total})}</h2><p className="text-navy-600">{t('practice.answeredOf',{done:Object.keys(answers).length,total})}</p></div><Owl variant="waving" className="size-20" /></div><ol className="mt-5 space-y-4">{data?.questions.map((q)=><li key={q.id} className="rounded-card bg-tint-100/60 p-4"><h3 className="font-bold text-navy-900">{q.position}. {q.prompt}</h3>{q.options.length?<ul className="mt-3 space-y-2">{q.options.map((option,index)=><li key={option}><label className={`block rounded-xl px-4 py-3 ${answers[q.position]===index?'bg-navy-800 text-white':'bg-white'}`}><input className="sr-only" type="radio" name={String(q.position)} checked={answers[q.position]===index} onChange={()=>save(q.position,index)} />{option}</label></li>)}</ul>:<textarea defaultValue={answers[q.position]??''} onBlur={(event)=>event.target.value.trim()&&save(q.position,event.target.value)} className="mt-3 min-h-24 w-full rounded-xl bg-white p-3" />}</li>)}</ol><div className="mt-5 pb-4"><Button disabled={!data||Object.keys(answers).length!==total} onClick={submit}>{t('practice.submit')}</Button></div></div></main>;};
