import { readFile } from 'node:fs/promises';

import { unzipSync, strFromU8 } from 'fflate';

import { INGEST_ERROR_CODES, IngestError } from './errors.js';

/**
 * Text extraction for Office documents and plain text files.
 *
 * Word, Excel and PowerPoint are all the same thing underneath — a ZIP of XML
 * parts (OOXML) — so they share one reader here rather than pulling in three
 * libraries that each bundle their own. PowerPoint has no mature extractor on
 * npm anyway, so at least part of this had to be written either way.
 *
 * What the three have in common beyond the container is the unit a student
 * cites: a slide, a sheet, a page. Each extractor below returns numbered
 * `sections`, which chunk exactly like PDF pages do, so "Source: Week 3.pptx,
 * slide 12" works the same way "page 12" already does.
 *
 * XML is read with regular expressions rather than a parser. That is a real
 * constraint and worth naming: it works here because these parts are
 * machine-generated by Office, never hand-written, and only the text runs are
 * being pulled out — no attributes to resolve, no namespaces to honour, no
 * structure to rebuild. A general XML parser would be the right call the moment
 * that stops being true.
 */

const FREE_SECTION_LIMIT = 50;

/** Plain-text formats, which never reach the ZIP path. */
const PLAIN_TEXT_MIME_TYPES = new Set([
  'text/plain',
  'text/markdown',
  'text/csv',
]);

/**
 * The formats this module reads, and what to call each one.
 *
 * `unit` is the word a student sees for a numbered part, because "page 4" of a
 * spreadsheet means nothing. `limitUnit` is the plural for the plan-limit
 * message.
 */
export const OFFICE_FORMATS = {
  docx: {
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    label: 'Word document',
    unit: 'section',
    limitUnit: 'sections',
  },
  xlsx: {
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    label: 'Excel spreadsheet',
    unit: 'sheet',
    limitUnit: 'sheets',
  },
  pptx: {
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    label: 'PowerPoint presentation',
    unit: 'slide',
    limitUnit: 'slides',
  },
  text: {
    mimeType: 'text/plain',
    label: 'Text file',
    unit: 'section',
    limitUnit: 'sections',
  },
};

// ---------------------------------------------------------------------------
// XML helpers
// ---------------------------------------------------------------------------

/**
 * The five predefined XML entities, plus numeric references.
 *
 * `&amp;` is unescaped LAST and deliberately: doing it first would turn a
 * literal `&amp;lt;` — which is how a document containing the text "&lt;"
 * stores it — into `<`, injecting markup into what should stay as characters.
 */
const decodeXmlEntities = (text) =>
  String(text)
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(Number.parseInt(dec, 10)))
    .replace(/&amp;/g, '&');

/**
 * Pulls the text out of every `<tag>...</tag>` in document order.
 *
 * The tag is matched with an optional namespace prefix, because the same run
 * element is `<w:t>` in Word and `<a:t>` in PowerPoint drawings, and some
 * producers emit it unprefixed.
 */
const textRuns = (xml, tag) => {
  const pattern = new RegExp(`<(?:[a-zA-Z0-9]+:)?${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</(?:[a-zA-Z0-9]+:)?${tag}>`, 'g');
  const runs = [];
  let match;
  while ((match = pattern.exec(xml)) !== null) runs.push(decodeXmlEntities(match[1]));
  return runs;
};

/** Splits a document into the elements named by `tag`, keeping their markup. */
const elements = (xml, tag) => {
  const pattern = new RegExp(`<(?:[a-zA-Z0-9]+:)?${tag}(?:\\s[^>]*)?>[\\s\\S]*?</(?:[a-zA-Z0-9]+:)?${tag}>`, 'g');
  return xml.match(pattern) ?? [];
};

/** Reads one attribute off an element's opening tag. */
const attribute = (element, name) =>
  new RegExp(`\\s${name}="([^"]*)"`).exec(element)?.[1] ?? null;

/** Files in an OOXML package are named with forward slashes, always. */
const entry = (zip, path) => zip[path];

const textOf = (zip, path) => {
  const file = entry(zip, path);
  return file ? strFromU8(file) : null;
};

// ---------------------------------------------------------------------------
// Word
// ---------------------------------------------------------------------------

/**
 * Word has no pages.
 *
 * Pagination is a property of rendering, not of the file — the page a
 * paragraph lands on depends on the font and paper size of whoever opens it,
 * and `document.xml` records nothing about it. So a Word document is divided
 * into numbered SECTIONS of roughly `paragraphsPerSection` paragraphs, and the
 * unit is named "section" rather than "page" so a citation never claims a
 * precision the format cannot support.
 */
const extractDocx = (zip, { paragraphsPerSection = 40 } = {}) => {
  const xml = textOf(zip, 'word/document.xml');
  if (xml === null) {
    throw new IngestError(
      INGEST_ERROR_CODES.EXTRACT_FAILED,
      'This Word file is missing its document body and may be corrupt.',
    );
  }

  const paragraphs = [];

  for (const paragraph of elements(xml, 'p')) {
    // A tab between cells keeps a table row readable on one line instead of
    // collapsing its cells into a single run-on string.
    const isTableRow = /<(?:[a-zA-Z0-9]+:)?tc[\s>]/.test(paragraph);
    const runs = textRuns(paragraph, 't');
    if (runs.length === 0) continue;

    const line = runs.join('').replace(/\s+/g, ' ').trim();
    if (line) paragraphs.push(isTableRow ? line : line);
  }

  // Table cells are their own <w:p> elements nested in rows, so a row arrives
  // as several paragraphs. Joining them is not worth the fidelity risk — each
  // cell reads as its own line, which chunks fine and cites fine.
  const sections = [];
  for (let i = 0; i < paragraphs.length; i += paragraphsPerSection) {
    const body = paragraphs.slice(i, i + paragraphsPerSection).join('\n').trim();
    if (body) {
      // Sections are this module's own division of a continuous document, so
      // unlike slides and sheets they genuinely are sequential with no gaps.
      sections.push({ number: sections.length + 1, title: null, text: body });
    }
  }

  return sections;
};

// ---------------------------------------------------------------------------
// Excel
// ---------------------------------------------------------------------------

/**
 * Excel stores most strings once, in a shared table, and cells hold indices
 * into it. A cell with `t="s"` means "look this up"; without it the value is
 * inline. Reading the value as literal text in the shared case yields a
 * spreadsheet full of integers, which is the classic way this goes wrong.
 */
const sharedStrings = (zip) => {
  const xml = textOf(zip, 'xl/sharedStrings.xml');
  if (!xml) return [];
  // One <si> may hold several <t> runs when parts of the cell are formatted
  // differently; they are one string and are joined.
  return elements(xml, 'si').map((si) => textRuns(si, 't').join(''));
};

/**
 * Dates are stored as a number of days since 1899-12-30 and are only dates
 * because of the cell's number format. Left alone they read as "45678", which
 * tells a student nothing and would have the model inventing meaning for it.
 *
 * The built-in date formats are ids 14-22 and 45-47; anything custom is
 * detected by looking for date tokens in its format string.
 */
const BUILTIN_DATE_FORMATS = new Set([14, 15, 16, 17, 18, 19, 20, 21, 22, 45, 46, 47]);

const dateFormatIds = (zip) => {
  const xml = textOf(zip, 'xl/styles.xml');
  if (!xml) return new Set();

  const customDateFormats = new Set();
  for (const numFmt of elements(xml, 'numFmts')) {
    for (const format of numFmt.match(/<(?:[a-zA-Z0-9]+:)?numFmt\s[^>]*\/>/g) ?? []) {
      const id = Number.parseInt(attribute(format, 'numFmtId') ?? '', 10);
      const code = attribute(format, 'formatCode') ?? '';
      // A format is a date format if it positions date tokens. Stripping
      // quoted literals first stops the "m" in a label like "Month" counting.
      const withoutLiterals = code.replace(/"[^"]*"/g, '');
      if (/[dmyhs]/i.test(withoutLiterals) && !/^[#0.,%\s]*$/.test(withoutLiterals)) {
        customDateFormats.add(id);
      }
    }
  }

  // cellXfs is positional: a cell's s="4" is an index into this list.
  const cellXfs = elements(xml, 'cellXfs')[0] ?? '';
  const styles = [];
  for (const xf of cellXfs.match(/<(?:[a-zA-Z0-9]+:)?xf\s[^>]*\/?>/g) ?? []) {
    styles.push(Number.parseInt(attribute(xf, 'numFmtId') ?? '0', 10));
  }

  const dateStyleIndices = new Set();
  styles.forEach((numFmtId, index) => {
    if (BUILTIN_DATE_FORMATS.has(numFmtId) || customDateFormats.has(numFmtId)) {
      dateStyleIndices.add(index);
    }
  });
  return dateStyleIndices;
};

/**
 * Excel's day 0 is 1899-12-30, not 1900-01-01 — the offset absorbs a leap-year
 * bug Lotus 1-2-3 had that Excel keeps for compatibility.
 */
const EXCEL_EPOCH_MS = Date.UTC(1899, 11, 30);

const serialToDate = (serial) => {
  const ms = EXCEL_EPOCH_MS + serial * 86_400_000;
  const date = new Date(ms);
  if (Number.isNaN(date.getTime())) return String(serial);
  const iso = date.toISOString();
  // A whole number is a date; a fraction carries a time of day worth keeping.
  return Number.isInteger(serial) ? iso.slice(0, 10) : iso.slice(0, 16).replace('T', ' ');
};

/** The column letters from a cell reference like "BC12". */
const columnOf = (reference) => /^([A-Z]+)/.exec(reference ?? '')?.[1] ?? '';
const rowOf = (reference) => Number.parseInt(/(\d+)$/.exec(reference ?? '')?.[1] ?? '0', 10);

/**
 * One sheet becomes one numbered section, its rows as tab-separated lines.
 *
 * Tabs rather than commas because cell values routinely contain commas, and a
 * student's spreadsheet is a table whose columns mean something — collapsing
 * them loses the association between a term and its definition, which is
 * exactly what a study kit is built from.
 */
const extractSheet = (xml, strings, dateStyles) => {
  const lines = [];

  for (const row of elements(xml, 'row')) {
    const cells = [];
    // Self-closing <c/> cells are empty and carry no <v>, so both shapes match.
    for (const cell of row.match(/<(?:[a-zA-Z0-9]+:)?c(?:\s[^>]*)?(?:\/>|>[\s\S]*?<\/(?:[a-zA-Z0-9]+:)?c>)/g) ?? []) {
      const type = attribute(cell, 't');
      const styleIndex = Number.parseInt(attribute(cell, 's') ?? '', 10);
      const reference = attribute(cell, 'r');

      let value;
      if (type === 's') {
        const index = Number.parseInt(textRuns(cell, 'v')[0] ?? '', 10);
        value = strings[index] ?? '';
      } else if (type === 'inlineStr') {
        value = textRuns(cell, 't').join('');
      } else if (type === 'str') {
        // A formula's cached result.
        value = textRuns(cell, 'v')[0] ?? '';
      } else if (type === 'b') {
        value = textRuns(cell, 'v')[0] === '1' ? 'TRUE' : 'FALSE';
      } else {
        const raw = textRuns(cell, 'v')[0];
        if (raw === undefined) {
          value = '';
        } else if (!Number.isNaN(styleIndex) && dateStyles.has(styleIndex) && raw !== '') {
          value = serialToDate(Number.parseFloat(raw));
        } else {
          value = raw;
        }
      }

      if (value !== '' && value !== undefined) {
        cells.push({ column: columnOf(reference), value: String(value).replace(/\s+/g, ' ').trim() });
      }
    }

    if (cells.length > 0) {
      lines.push({ row: rowOf(attribute(row, 'r')), text: cells.map((c) => c.value).join('\t') });
    }
  }

  return lines
    .filter((line) => line.text.trim())
    .map((line) => line.text)
    .join('\n');
};

/**
 * Sheet order comes from workbook.xml, not from the order of files in the ZIP.
 * A workbook whose sheets were reordered in Excel keeps its original file names,
 * so reading the directory would number them wrongly.
 */
const extractXlsx = (zip) => {
  const workbook = textOf(zip, 'xl/workbook.xml');
  if (workbook === null) {
    throw new IngestError(
      INGEST_ERROR_CODES.EXTRACT_FAILED,
      'This Excel file is missing its workbook and may be corrupt.',
    );
  }

  const strings = sharedStrings(zip);
  const dateStyles = dateFormatIds(zip);

  // r:id -> target path, from the workbook's relationships.
  const relsXml = textOf(zip, 'xl/_rels/workbook.xml.rels') ?? '';
  const relationships = new Map();
  for (const rel of relsXml.match(/<Relationship\s[^>]*\/?>/g) ?? []) {
    const id = attribute(rel, 'Id');
    const target = attribute(rel, 'Target');
    if (id && target) relationships.set(id, target.replace(/^\/?xl\//, '').replace(/^\//, ''));
  }

  const sections = [];
  const sheetElements = workbook.match(/<(?:[a-zA-Z0-9]+:)?sheet\s[^>]*\/?>/g) ?? [];

  sheetElements.forEach((sheet, index) => {
    const name = attribute(sheet, 'name') ?? `Sheet${index + 1}`;
    const relationshipId = attribute(sheet, 'r:id') ?? attribute(sheet, 'id');
    const target = relationshipId ? relationships.get(relationshipId) : null;
    const path = `xl/${target ?? `worksheets/sheet${index + 1}.xml`}`;

    const sheetXml = textOf(zip, path);
    if (sheetXml === null) return;

    const body = extractSheet(sheetXml, strings, dateStyles);
    if (body.trim()) {
      // The sheet name leads the section: it is often the only label saying
      // what the table is, and a citation reads better with it.
      sections.push({
        // Position in the workbook, not a count of the sheets that had
        // content: an empty sheet in the middle must not renumber the ones
        // after it, or a citation opens the wrong tab.
        number: index + 1,
        title: name,
        text: `${name}\n${body}`,
      });
    }
  });

  return sections;
};

// ---------------------------------------------------------------------------
// PowerPoint
// ---------------------------------------------------------------------------

/**
 * Slide order comes from the presentation's relationships, for the same reason
 * sheet order does: `slide12.xml` is a file name, not a position. Reordering a
 * deck in PowerPoint rewrites the relationship list and leaves the file names
 * alone, so numbering by file name would cite the wrong slide.
 */
const slidePaths = (zip) => {
  const presentation = textOf(zip, 'ppt/presentation.xml');
  const relsXml = textOf(zip, 'ppt/_rels/presentation.xml.rels');

  if (presentation && relsXml) {
    const relationships = new Map();
    for (const rel of relsXml.match(/<Relationship\s[^>]*\/?>/g) ?? []) {
      const id = attribute(rel, 'Id');
      const target = attribute(rel, 'Target');
      if (id && target) relationships.set(id, target.replace(/^\.\.\//, '').replace(/^\//, ''));
    }

    const ordered = [];
    for (const sldId of presentation.match(/<(?:[a-zA-Z0-9]+:)?sldId\s[^>]*\/?>/g) ?? []) {
      const relationshipId = attribute(sldId, 'r:id') ?? attribute(sldId, 'id');
      const target = relationshipId ? relationships.get(relationshipId) : null;
      if (target) ordered.push(target.startsWith('ppt/') ? target : `ppt/${target}`);
    }
    if (ordered.length > 0) return ordered;
  }

  // Fallback for a deck without a readable relationship list: file order, but
  // sorted NUMERICALLY, or slide10 sorts before slide2.
  return Object.keys(zip)
    .filter((path) => /^ppt\/slides\/slide\d+\.xml$/.test(path))
    .sort((a, b) => {
      const n = (p) => Number.parseInt(/(\d+)\.xml$/.exec(p)[1], 10);
      return n(a) - n(b);
    });
};

/**
 * Finds a slide's speaker notes, through that slide's own relationships.
 *
 * Deriving the path from the slide number does not work, and fails quietly
 * when it does: only slides that HAVE notes get a notesSlide, so a deck with
 * notes on slides 3, 5, 7 and 9 stores them as notesSlide1 through 4. Pairing
 * them by number attaches slide 3's notes to slide 1 — plausible-looking text
 * on the wrong slide, which is worse than no notes at all.
 *
 * The part name is also `notesSlide1.xml`, capital S; a lowercased guess finds
 * nothing on a case-sensitive lookup and silently yields no notes.
 */
const notesFor = (zip, slidePath) => {
  const name = slidePath.split('/').pop();
  const relsXml = textOf(zip, `ppt/slides/_rels/${name}.rels`);
  if (!relsXml) return null;

  for (const rel of relsXml.match(/<Relationship\s[^>]*\/?>/g) ?? []) {
    if (!/notesSlide$/.test(attribute(rel, 'Type') ?? '')) continue;
    const target = attribute(rel, 'Target');
    if (!target) continue;
    // Targets are relative to ppt/slides/, so "../notesSlides/notesSlide1.xml".
    const path = target.replace(/^\.\.\//, 'ppt/').replace(/^\//, '');
    return textOf(zip, path.startsWith('ppt/') ? path : `ppt/slides/${path}`);
  }
  return null;
};

/**
 * One slide becomes one numbered section: its own text, then its speaker notes.
 *
 * The notes are included because on a lecture deck they are frequently where
 * the actual explanation lives — the slide says "Normalization: 3 rules" and
 * the notes say what the three rules are. Dropping them would throw away the
 * more useful half of the file.
 */
const extractPptx = (zip) => {
  const sections = [];

  slidePaths(zip).forEach((path, index) => {
    const xml = textOf(zip, path);
    if (xml === null) return;

    // <a:t> is the DrawingML text run — the same element for a title, a bullet
    // and a text box, which is why paragraphs are recovered from <a:p> instead.
    const lines = elements(xml, 'p')
      .map((paragraph) => textRuns(paragraph, 't').join('').replace(/\s+/g, ' ').trim())
      .filter(Boolean);

    const slideNumber = index + 1;
    const notesXml = notesFor(zip, path);
    const notes = notesXml
      ? elements(notesXml, 'p')
          .map((paragraph) => textRuns(paragraph, 't').join('').replace(/\s+/g, ' ').trim())
          .filter(Boolean)
          // PowerPoint puts the slide number itself in the notes placeholder;
          // it is not content and would just repeat as a stray digit.
          .filter((line) => line !== String(slideNumber))
      : [];

    const body = [
      lines.join('\n'),
      notes.length > 0 ? `Speaker notes: ${notes.join(' ')}` : '',
    ]
      .filter(Boolean)
      .join('\n')
      .trim();

    if (body) {
      // Numbered by POSITION IN THE DECK, not by how many slides survived.
      // A slide that is only a picture yields no text and is dropped, and
      // numbering by the surviving count would silently shift every slide
      // after it — a citation reading "slide 5" would open slide 6. The
      // numbers are allowed to skip instead.
      sections.push({ number: slideNumber, title: lines[0] ?? null, text: body });
    }
  });

  return sections;
};

// ---------------------------------------------------------------------------
// Plain text
// ---------------------------------------------------------------------------

/**
 * Plain text is one section. It has no numbered parts to cite, and inventing
 * some by counting lines would give the tutor a "section 4" that corresponds to
 * nothing the student can find in their file.
 */
const extractPlainText = (buffer) => {
  const text = buffer.toString('utf8').replace(/\r\n/g, '\n').trim();
  return text ? [{ number: 1, title: null, text }] : [];
};

// ---------------------------------------------------------------------------
// Format detection and entry point
// ---------------------------------------------------------------------------

/**
 * Identifies an OOXML package by what is inside it rather than by its name.
 *
 * A file renamed from .xlsx to .docx passes every check made before this one —
 * the extension matches what the browser claimed and the magic bytes say "ZIP",
 * which is true of all three formats. Reading the package tells the truth, and
 * turns a confusing parse failure into an accurate message.
 */
export const detectOoxmlFormat = (zip) => {
  if (entry(zip, 'word/document.xml')) return 'docx';
  if (entry(zip, 'xl/workbook.xml')) return 'xlsx';
  if (entry(zip, 'ppt/presentation.xml')) return 'pptx';
  return null;
};

/** Maps a stored mime type to the format key this module extracts by. */
export const formatForMimeType = (mimeType) => {
  if (PLAIN_TEXT_MIME_TYPES.has(mimeType)) return 'text';
  return Object.keys(OFFICE_FORMATS).find((key) => OFFICE_FORMATS[key].mimeType === mimeType) ?? null;
};

/**
 * Extracts text from a document.
 *
 * Returns the same shape the PDF extractor does, with `sections` in place of
 * `pages`, so the ingest service treats a deck and a PDF the same way.
 *
 * @param {string|Buffer} source   File path, or the bytes themselves.
 * @param {{ mimeType?: string, planTier?: string }} [options]
 */
export const extractDocument = async (source, { mimeType, planTier = 'free' } = {}) => {
  const buffer = Buffer.isBuffer(source) ? source : await readFile(source);

  if (buffer.length === 0) {
    throw new IngestError(
      INGEST_ERROR_CODES.EXTRACT_FAILED,
      'This file is empty. Please upload it again.',
    );
  }

  const claimed = formatForMimeType(mimeType);
  let format = claimed;
  let sections;

  if (claimed === 'text') {
    sections = extractPlainText(buffer);
  } else {
    let zip;
    try {
      zip = unzipSync(new Uint8Array(buffer));
    } catch (err) {
      throw new IngestError(
        INGEST_ERROR_CODES.EXTRACT_FAILED,
        `This file could not be opened — it may be corrupt or password-protected (${err.message}).`,
      );
    }

    // What the package actually is beats what the upload claimed.
    format = detectOoxmlFormat(zip);
    if (!format) {
      throw new IngestError(
        INGEST_ERROR_CODES.EXTRACT_FAILED,
        'This does not look like a Word, Excel or PowerPoint file.',
      );
    }

    if (format === 'docx') sections = extractDocx(zip);
    else if (format === 'xlsx') sections = extractXlsx(zip);
    else sections = extractPptx(zip);
  }

  const { unit, limitUnit, label } = OFFICE_FORMATS[format];

  if (sections.length === 0) {
    throw new IngestError(
      INGEST_ERROR_CODES.EMPTY_CONTENT,
      `No readable text could be found in this ${label.toLowerCase()}.`,
    );
  }

  // Charged against the same free-plan allowance a PDF's pages are, and checked
  // AFTER extraction rather than before: unlike a PDF, none of these formats
  // records how many parts it has without reading them.
  if (planTier !== 'plus' && sections.length > FREE_SECTION_LIMIT) {
    throw new IngestError(
      INGEST_ERROR_CODES.PAGE_LIMIT_EXCEEDED,
      `Free plan allows up to ${FREE_SECTION_LIMIT} ${limitUnit} per document ` +
        `(this one has ${sections.length}). Please upgrade to Plus for larger documents.`,
      { sectionCount: sections.length, limit: FREE_SECTION_LIMIT, unit },
    );
  }

  const fullText = sections.map((section) => section.text).join('\n\n').trim();

  if (!fullText) {
    throw new IngestError(
      INGEST_ERROR_CODES.EMPTY_CONTENT,
      `No readable text could be found in this ${label.toLowerCase()}.`,
    );
  }

  return { format, label, unit, sectionCount: sections.length, sections, fullText };
};
